In [199]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [200]:
df=pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [201]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [202]:
cols = ['mainroad','guestroom','basement','hotwaterheating',
        'airconditioning','prefarea','furnishingstatus']

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[cols])

encoded_df = pd.DataFrame(
    encoded,# has the encoded data stored
    columns=encoder.get_feature_names_out(cols)  # this will takes out columns names from cols
)

In [203]:

df = df.drop(columns=cols)# will drop the original columns in df datset

df = pd.concat([df, encoded_df], axis=1)  # merging orginal datset with encoded data 
df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1,12250000,8960,4,4,4,3,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
2,12250000,9960,3,2,2,2,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,12215000,7500,4,2,2,3,0.0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
4,11410000,7420,4,1,2,2,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [204]:
poly=PolynomialFeatures(degree=2,interaction_only=True,include_bias=False)
df_poly_converted_data=poly.fit_transform(df)

In [205]:
df_poly_converted_data   # this is in array not i dataframe

array([[1.330e+07, 7.420e+03, 4.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.225e+07, 8.960e+03, 4.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.225e+07, 9.960e+03, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [1.750e+06, 3.620e+03, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.750e+06, 2.910e+03, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.750e+06, 3.850e+03, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]], shape=(545, 231))

In [206]:
df_poly = pd.DataFrame(
    df_poly_converted_data,
    columns=poly.get_feature_names_out(df.columns)
)
df_poly

,price,area,bedrooms,bathrooms,stories,parking,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,...,prefarea_no prefarea_yes,prefarea_no furnishingstatus_furnished,prefarea_no furnishingstatus_semi-furnished,prefarea_no furnishingstatus_unfurnished,prefarea_yes furnishingstatus_furnished,prefarea_yes furnishingstatus_semi-furnished,prefarea_yes furnishingstatus_unfurnished,furnishingstatus_furnished furnishingstatus_semi-furnished,furnishingstatus_furnished furnishingstatus_unfurnished,furnishingstatus_semi-furnished furnishingstatus_unfurnished
0,13300000.0,7420.0,4.0,2.0,3.0,2.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,12250000.0,8960.0,4.0,4.0,4.0,3.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12250000.0,9960.0,3.0,2.0,2.0,2.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,12215000.0,7500.0,4.0,2.0,2.0,3.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,11410000.0,7420.0,4.0,1.0,2.0,2.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000.0,3000.0,2.0,1.0,1.0,2.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
541,1767150.0,2400.0,3.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
542,1750000.0,3620.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
543,1750000.0,2910.0,3.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
544,1750000.0,3850.0,3.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [207]:
model=LinearRegression()
i=0
kf=KFold(n_splits=5,shuffle=True,random_state=42)
for train,test in kf.split(df_poly):
    x_train,x_test=df_poly.iloc[train],df_poly.iloc[test]
    y_train,y_test=y.iloc[train],y.iloc[test]
    model.fit(x_train,y_train)
    print("Fold ",i," Cross-valid-score: ",model.score(x_test,y_test))
    i=i+1

Fold  0  Cross-valid-score:  1.0
Fold  1  Cross-valid-score:  1.0
Fold  2  Cross-valid-score:  1.0
Fold  3  Cross-valid-score:  1.0
Fold  4  Cross-valid-score:  1.0

In [ ]:
print(model.predict(df_poly.iloc[[0]]))  # for first row

[13299999.99999997]